UPDATE public.countries SET country = 'Algeria', shortname = 'dz' WHERE id = 1;
UPDATE public.countries SET country = 'Angola', shortname = 'ao' WHERE id = 2;
UPDATE public.countries SET country = 'Benin', shortname = 'bj' WHERE id = 3;
UPDATE public.countries SET country = 'Botswana', shortname = 'bw' WHERE id = 4;
UPDATE public.countries SET country = 'Burkina Faso', shortname = 'bf' WHERE id = 5;
UPDATE public.countries SET country = 'Burundi', shortname = 'bi' WHERE id = 6;
UPDATE public.countries SET country = 'Cameroon', shortname = 'cm' WHERE id = 7;
UPDATE public.countries SET country = 'Cape Verde', shortname = 'cv' WHERE id = 8;
UPDATE public.countries SET country = 'Central African Republic', shortname = 'cf' WHERE id = 9;
UPDATE public.countries SET country = 'Chad', shortname = 'td' WHERE id = 10;
UPDATE public.countries SET country = 'Comoros', shortname = 'km' WHERE id = 11;
UPDATE public.countries SET country = 'Congo', shortname = 'cg' WHERE id = 12;
UPDATE public.countries SET country = 'Congo, The Democratic Republic of the', shortname = 'cd' WHERE id = 13;
UPDATE public.countries SET country = 'CÃ´te d''Ivoire', shortname = 'ci' WHERE id = 14;
UPDATE public.countries SET country = 'Djibouti', shortname = 'dj' WHERE id = 15;
UPDATE public.countries SET country = 'Egypt', shortname = 'eg' WHERE id = 16;
UPDATE public.countries SET country = 'Equatorial Guinea', shortname = 'gq' WHERE id = 17;
UPDATE public.countries SET country = 'Eritrea', shortname = 'er' WHERE id = 18;
UPDATE public.countries SET country = 'Ethiopia', shortname = 'et' WHERE id = 19;
UPDATE public.countries SET country = 'Gabon', shortname = 'ga' WHERE id = 20;
UPDATE public.countries SET country = 'Gambia', shortname = 'gm' WHERE id = 21;
UPDATE public.countries SET country = 'Ghana', shortname = 'gh' WHERE id = 22;
UPDATE public.countries SET country = 'Guinea', shortname = 'gn' WHERE id = 23;
UPDATE public.countries SET country = 'Guinea-Bissau', shortname = 'gw' WHERE id = 24;
UPDATE public.countries SET country = 'Kenya', shortname = 'ke' WHERE id = 25;
UPDATE public.countries SET country = 'Lesotho', shortname = 'ls' WHERE id = 26;
UPDATE public.countries SET country = 'Liberia', shortname = 'lr' WHERE id = 27;
UPDATE public.countries SET country = 'Libya', shortname = 'ly' WHERE id = 28;
UPDATE public.countries SET country = 'Madagascar', shortname = 'mg' WHERE id = 29;
UPDATE public.countries SET country = 'Malawi', shortname = 'mw' WHERE id = 30;
UPDATE public.countries SET country = 'Mali', shortname = 'ml' WHERE id = 31;
UPDATE public.countries SET country = 'Mauritania', shortname = 'mr' WHERE id = 32;
UPDATE public.countries SET country = 'Mauritius', shortname = 'mu' WHERE id = 33;
UPDATE public.countries SET country = 'Mayotte', shortname = 'yt' WHERE id = 34;
UPDATE public.countries SET country = 'Morocco', shortname = 'ma' WHERE id = 35;
UPDATE public.countries SET country = 'Mozambique', shortname = 'mz' WHERE id = 36;
UPDATE public.countries SET country = 'Namibia', shortname = 'na' WHERE id = 37;
UPDATE public.countries SET country = 'Niger', shortname = 'ne' WHERE id = 38;
UPDATE public.countries SET country = 'Nigeria', shortname = 'ng' WHERE id = 39;
UPDATE public.countries SET country = 'Rwanda', shortname = 'rw' WHERE id = 40;
UPDATE public.countries SET country = 'RÃ©union', shortname = 're' WHERE id = 41;
UPDATE public.countries SET country = 'Saint Helena', shortname = 'sh' WHERE id = 42;
UPDATE public.countries SET country = 'Sao Tome and Principe', shortname = 'st' WHERE id = 43;
UPDATE public.countries SET country = 'Senegal', shortname = 'sn' WHERE id = 44;
UPDATE public.countries SET country = 'Seychelles', shortname = 'sc' WHERE id = 45;
UPDATE public.countries SET country = 'Sierra Leone', shortname = 'sl' WHERE id = 46;
UPDATE public.countries SET country = 'Somalia', shortname = 'so' WHERE id = 47;
UPDATE public.countries SET country = 'South Africa', shortname = 'za' WHERE id = 48;
UPDATE public.countries SET country = 'South Sudan', shortname = 'ss' WHERE id = 49;
UPDATE public.countries SET country = 'Sudan', shortname = 'sd' WHERE id = 50;
UPDATE public.countries SET country = 'Swaziland', shortname = 'sz' WHERE id = 51;
UPDATE public.countries SET country = 'Tanzania', shortname = 'tz' WHERE id = 52;
UPDATE public.countries SET country = 'Togo', shortname = 'tg' WHERE id = 53;
UPDATE public.countries SET country = 'Tunisia', shortname = 'tn' WHERE id = 54;
UPDATE public.countries SET country = 'Uganda', shortname = 'ug' WHERE id = 55;
UPDATE public.countries SET country = 'Western Sahara', shortname = 'eh' WHERE id = 56;
UPDATE public.countries SET country = 'Zambia', shortname = 'zm' WHERE id = 57;
UPDATE public.countries SET country = 'Zimbabwe', shortname = 'zw' WHERE id = 58;
UPDATE public.countries SET country = 'Anguilla', shortname = 'ai' WHERE id = 59;
UPDATE public.countries SET country = 'Antigua and Barbuda', shortname = 'ag' WHERE id = 60;
UPDATE public.countries SET country = 'Argentina', shortname = 'ar' WHERE id = 61;
UPDATE public.countries SET country = 'Aruba', shortname = 'aw' WHERE id = 62;
UPDATE public.countries SET country = 'Bahamas', shortname = 'bs' WHERE id = 63;
UPDATE public.countries SET country = 'Barbados', shortname = 'bb' WHERE id = 64;
UPDATE public.countries SET country = 'Belize', shortname = 'bz' WHERE id = 65;
UPDATE public.countries SET country = 'Bermuda', shortname = 'bm' WHERE id = 66;
UPDATE public.countries SET country = 'Bolivia, Plurinational State of', shortname = 'bo' WHERE id = 67;
UPDATE public.countries SET country = 'Brazil', shortname = 'br' WHERE id = 68;
UPDATE public.countries SET country = 'Canada', shortname = 'ca' WHERE id = 69;
UPDATE public.countries SET country = 'Cayman Islands', shortname = 'ky' WHERE id = 70;
UPDATE public.countries SET country = 'Chile', shortname = 'cl' WHERE id = 71;
UPDATE public.countries SET country = 'Colombia', shortname = 'co' WHERE id = 72;
UPDATE public.countries SET country = 'Costa Rica', shortname = 'cr' WHERE id = 73;
UPDATE public.countries SET country = 'Cuba', shortname = 'cu' WHERE id = 74;
UPDATE public.countries SET country = 'CuraÃ§ao', shortname = 'cw' WHERE id = 75;
UPDATE public.countries SET country = 'Dominica', shortname = 'dm' WHERE id = 76;
UPDATE public.countries SET country = 'Dominican Republic', shortname = 'do' WHERE id = 77;
UPDATE public.countries SET country = 'Ecuador', shortname = 'ec' WHERE id = 78;
UPDATE public.countries SET country = 'El Salvador', shortname = 'sv' WHERE id = 79;
UPDATE public.countries SET country = 'Falkland Islands (Malvinas)', shortname = 'fk' WHERE id = 80;
UPDATE public.countries SET country = 'French Guiana', shortname = 'gf' WHERE id = 81;
UPDATE public.countries SET country = 'Greenland', shortname = 'gl' WHERE id = 82;
UPDATE public.countries SET country = 'Grenada', shortname = 'gd' WHERE id = 83;
UPDATE public.countries SET country = 'Guadeloupe', shortname = 'gp' WHERE id = 84;
UPDATE public.countries SET country = 'Guatemala', shortname = 'gt' WHERE id = 85;
UPDATE public.countries SET country = 'Guyana', shortname = 'gy' WHERE id = 86;
UPDATE public.countries SET country = 'Haiti', shortname = 'ht' WHERE id = 87;
UPDATE public.countries SET country = 'Honduras', shortname = 'hn' WHERE id = 88;
UPDATE public.countries SET country = 'Jamaica', shortname = 'jm' WHERE id = 89;
UPDATE public.countries SET country = 'Martinique', shortname = 'mq' WHERE id = 90;
UPDATE public.countries SET country = 'Mexico', shortname = 'mx' WHERE id = 91;
UPDATE public.countries SET country = 'Montserrat', shortname = 'ms' WHERE id = 92;
UPDATE public.countries SET country = 'Netherlands Antilles', shortname = 'an' WHERE id = 93;
UPDATE public.countries SET country = 'Nicaragua', shortname = 'ni' WHERE id = 94;
UPDATE public.countries SET country = 'Panama', shortname = 'pa' WHERE id = 95;
UPDATE public.countries SET country = 'Paraguay', shortname = 'py' WHERE id = 96;
UPDATE public.countries SET country = 'Peru', shortname = 'pe' WHERE id = 97;
UPDATE public.countries SET country = 'Puerto Rico', shortname = 'pr' WHERE id = 98;
UPDATE public.countries SET country = 'Saint Kitts and Nevis', shortname = 'kn' WHERE id = 99;
UPDATE public.countries SET country = 'Saint Lucia', shortname = 'lc' WHERE id = 100;
UPDATE public.countries SET country = 'Saint Pierre and Miquelon', shortname = 'pm' WHERE id = 101;
UPDATE public.countries SET country = 'Saint Vincent and the Grenadines', shortname = 'vc' WHERE id = 102;
UPDATE public.countries SET country = 'Sint Maarten', shortname = 'sx' WHERE id = 103;
UPDATE public.countries SET country = 'Suriname', shortname = 'sr' WHERE id = 104;
UPDATE public.countries SET country = 'Trinidad and Tobago', shortname = 'tt' WHERE id = 105;
UPDATE public.countries SET country = 'Turks and Caicos Islands', shortname = 'tc' WHERE id = 106;
UPDATE public.countries SET country = 'United States', shortname = 'us' WHERE id = 107;
UPDATE public.countries SET country = 'Uruguay', shortname = 'uy' WHERE id = 108;
UPDATE public.countries SET country = 'Venezuela, Bolivarian Republic of', shortname = 've' WHERE id = 109;
UPDATE public.countries SET country = 'Virgin Islands, British', shortname = 'vg' WHERE id = 110;
UPDATE public.countries SET country = 'Virgin Islands, U.S.', shortname = 'vi' WHERE id = 111;
UPDATE public.countries SET country = 'Afghanistan', shortname = 'af' WHERE id = 112;
UPDATE public.countries SET country = 'Armenia', shortname = 'am' WHERE id = 113;
UPDATE public.countries SET country = 'Azerbaijan', shortname = 'az' WHERE id = 114;
UPDATE public.countries SET country = 'Bahrain', shortname = 'bh' WHERE id = 115;
UPDATE public.countries SET country = 'Bangladesh', shortname = 'bd' WHERE id = 116;
UPDATE public.countries SET country = 'Bhutan', shortname = 'bt' WHERE id = 117;
UPDATE public.countries SET country = 'Brunei Darussalam', shortname = 'bn' WHERE id = 118;
UPDATE public.countries SET country = 'Cambodia', shortname = 'kh' WHERE id = 119;
UPDATE public.countries SET country = 'China', shortname = 'cn' WHERE id = 120;
UPDATE public.countries SET country = 'Cyprus', shortname = 'cy' WHERE id = 121;
UPDATE public.countries SET country = 'Georgia', shortname = 'ge' WHERE id = 122;
UPDATE public.countries SET country = 'Hong Kong', shortname = 'hk' WHERE id = 123;
UPDATE public.countries SET country = 'India', shortname = 'in' WHERE id = 124;
UPDATE public.countries SET country = 'Indonesia', shortname = 'id' WHERE id = 125;
UPDATE public.countries SET country = 'Iran, Islamic Republic of', shortname = 'ir' WHERE id = 126;
UPDATE public.countries SET country = 'Iraq', shortname = 'iq' WHERE id = 127;
UPDATE public.countries SET country = 'Israel', shortname = 'il' WHERE id = 128;
UPDATE public.countries SET country = 'Japan', shortname = 'jp' WHERE id = 129;
UPDATE public.countries SET country = 'Jordan', shortname = 'jo' WHERE id = 130;
UPDATE public.countries SET country = 'Kazakhstan', shortname = 'kz' WHERE id = 131;
UPDATE public.countries SET country = 'Korea, Democratic People''s Republic of', shortname = 'kp' WHERE id = 132;
UPDATE public.countries SET country = 'Korea, Republic of', shortname = 'kr' WHERE id = 133;
UPDATE public.countries SET country = 'Kuwait', shortname = 'kw' WHERE id = 134;
UPDATE public.countries SET country = 'Kyrgyzstan', shortname = 'kg' WHERE id = 135;
UPDATE public.countries SET country = 'Lao People''s Democratic Republic', shortname = 'la' WHERE id = 136;
UPDATE public.countries SET country = 'Lebanon', shortname = 'lb' WHERE id = 137;
UPDATE public.countries SET country = 'Macao', shortname = 'mo' WHERE id = 138;
UPDATE public.countries SET country = 'Malaysia', shortname = 'my' WHERE id = 139;
UPDATE public.countries SET country = 'Maldives', shortname = 'mv' WHERE id = 140;
UPDATE public.countries SET country = 'Mongolia', shortname = 'mn' WHERE id = 141;
UPDATE public.countries SET country = 'Myanmar', shortname = 'mm' WHERE id = 142;
UPDATE public.countries SET country = 'Nepal', shortname = 'np' WHERE id = 143;
UPDATE public.countries SET country = 'Oman', shortname = 'om' WHERE id = 144;
UPDATE public.countries SET country = 'Pakistan', shortname = 'pk' WHERE id = 145;
UPDATE public.countries SET country = 'Palestinian Territory, Occupied', shortname = 'ps' WHERE id = 146;
UPDATE public.countries SET country = 'Philippines', shortname = 'ph' WHERE id = 147;
UPDATE public.countries SET country = 'Qatar', shortname = 'qa' WHERE id = 148;
UPDATE public.countries SET country = 'Saudi Arabia', shortname = 'sa' WHERE id = 149;
UPDATE public.countries SET country = 'Singapore', shortname = 'sg' WHERE id = 150;
UPDATE public.countries SET country = 'Sri Lanka', shortname = 'lk' WHERE id = 151;
UPDATE public.countries SET country = 'Syrian Arab Republic', shortname = 'sy' WHERE id = 152;
UPDATE public.countries SET country = 'Taiwan, Province of China', shortname = 'tw' WHERE id = 153;
UPDATE public.countries SET country = 'Tajikistan', shortname = 'tj' WHERE id = 154;
UPDATE public.countries SET country = 'Thailand', shortname = 'th' WHERE id = 155;
UPDATE public.countries SET country = 'Timor-Leste', shortname = 'tl' WHERE id = 156;
UPDATE public.countries SET country = 'Turkey', shortname = 'tr' WHERE id = 157;
UPDATE public.countries SET country = 'Turkmenistan', shortname = 'tm' WHERE id = 158;
UPDATE public.countries SET country = 'United Arab Emirates', shortname = 'ae' WHERE id = 159;
UPDATE public.countries SET country = 'Uzbekistan', shortname = 'uz' WHERE id = 160;
UPDATE public.countries SET country = 'Viet Nam', shortname = 'vn' WHERE id = 161;
UPDATE public.countries SET country = 'Yemen', shortname = 'ye' WHERE id = 162;
UPDATE public.countries SET country = 'American Samoa', shortname = 'as' WHERE id = 163;
UPDATE public.countries SET country = 'Australia', shortname = 'au' WHERE id = 164;
UPDATE public.countries SET country = 'Cook Islands', shortname = 'ck' WHERE id = 165;
UPDATE public.countries SET country = 'Fiji', shortname = 'fj' WHERE id = 166;
UPDATE public.countries SET country = 'French Polynesia', shortname = 'pf' WHERE id = 167;
UPDATE public.countries SET country = 'Guam', shortname = 'gu' WHERE id = 168;
UPDATE public.countries SET country = 'Kiribati', shortname = 'ki' WHERE id = 169;
UPDATE public.countries SET country = 'Marshall Islands', shortname = 'mh' WHERE id = 170;
UPDATE public.countries SET country = 'Micronesia, Federated States of', shortname = 'fm' WHERE id = 171;
UPDATE public.countries SET country = 'Nauru', shortname = 'nr' WHERE id = 172;
UPDATE public.countries SET country = 'New Caledonia', shortname = 'nc' WHERE id = 173;
UPDATE public.countries SET country = 'New Zealand', shortname = 'nz' WHERE id = 174;
UPDATE public.countries SET country = 'Niue', shortname = 'nu' WHERE id = 175;
UPDATE public.countries SET country = 'Norfolk Island', shortname = 'nf' WHERE id = 176;
UPDATE public.countries SET country = 'Northern Mariana Islands', shortname = 'mp' WHERE id = 177;
UPDATE public.countries SET country = 'Palau', shortname = 'pw' WHERE id = 178;
UPDATE public.countries SET country = 'Papua New Guinea', shortname = 'pg' WHERE id = 179;
UPDATE public.countries SET country = 'Pitcairn', shortname = 'pn' WHERE id = 180;
UPDATE public.countries SET country = 'Samoa', shortname = 'ws' WHERE id = 181;
UPDATE public.countries SET country = 'Solomon Islands', shortname = 'sb' WHERE id = 182;
UPDATE public.countries SET country = 'Tokelau', shortname = 'tk' WHERE id = 183;
UPDATE public.countries SET country = 'Tonga', shortname = 'to' WHERE id = 184;
UPDATE public.countries SET country = 'Tuvalu', shortname = 'tv' WHERE id = 185;
UPDATE public.countries SET country = 'Vanuatu', shortname = 'vu' WHERE id = 186;
UPDATE public.countries SET country = 'Wallis and Futuna', shortname = 'wf' WHERE id = 187;
UPDATE public.countries SET country = 'Albania', shortname = 'al' WHERE id = 188;
UPDATE public.countries SET country = 'Andorra', shortname = 'ad' WHERE id = 189;
UPDATE public.countries SET country = 'Austria', shortname = 'at' WHERE id = 190;
UPDATE public.countries SET country = 'Belarus', shortname = 'by' WHERE id = 191;
UPDATE public.countries SET country = 'Belgium', shortname = 'be' WHERE id = 192;
UPDATE public.countries SET country = 'Bosnia and Herzegovina', shortname = 'ba' WHERE id = 193;
UPDATE public.countries SET country = 'Bulgaria', shortname = 'bg' WHERE id = 194;
UPDATE public.countries SET country = 'Croatia', shortname = 'hr' WHERE id = 195;
UPDATE public.countries SET country = 'Czech Republic', shortname = 'cz' WHERE id = 196;
UPDATE public.countries SET country = 'Denmark', shortname = 'dk' WHERE id = 197;
UPDATE public.countries SET country = 'Estonia', shortname = 'ee' WHERE id = 198;
UPDATE public.countries SET country = 'Faroe Islands', shortname = 'fo' WHERE id = 199;
UPDATE public.countries SET country = 'Finland', shortname = 'fi' WHERE id = 200;
UPDATE public.countries SET country = 'France', shortname = 'fr' WHERE id = 201;
UPDATE public.countries SET country = 'Germany', shortname = 'de' WHERE id = 202;
UPDATE public.countries SET country = 'Gibraltar', shortname = 'gi' WHERE id = 203;
UPDATE public.countries SET country = 'Greece', shortname = 'gr' WHERE id = 204;
UPDATE public.countries SET country = 'Holy See (Vatican City State)', shortname = 'va' WHERE id = 205;
UPDATE public.countries SET country = 'Hungary', shortname = 'hu' WHERE id = 206;
UPDATE public.countries SET country = 'Iceland', shortname = 'is' WHERE id = 207;
UPDATE public.countries SET country = 'Ireland', shortname = 'ie' WHERE id = 208;
UPDATE public.countries SET country = 'Italy', shortname = 'it' WHERE id = 209;
UPDATE public.countries SET country = 'Kosovo', shortname = 'xk' WHERE id = 210;
UPDATE public.countries SET country = 'Latvia', shortname = 'lv' WHERE id = 211;
UPDATE public.countries SET country = 'Liechtenstein', shortname = 'li' WHERE id = 212;
UPDATE public.countries SET country = 'Lithuania', shortname = 'lt' WHERE id = 213;
UPDATE public.countries SET country = 'Luxembourg', shortname = 'lu' WHERE id = 214;
UPDATE public.countries SET country = 'Macedonia, The Former Yugoslav Republic of', shortname = 'mk' WHERE id = 215;
UPDATE public.countries SET country = 'Malta', shortname = 'mt' WHERE id = 216;
UPDATE public.countries SET country = 'Moldova, Republic of', shortname = 'md' WHERE id = 217;
UPDATE public.countries SET country = 'Monaco', shortname = 'mc' WHERE id = 218;
UPDATE public.countries SET country = 'Montenegro', shortname = 'me' WHERE id = 219;
UPDATE public.countries SET country = 'Netherlands', shortname = 'nl' WHERE id = 220;
UPDATE public.countries SET country = 'Norway', shortname = 'no' WHERE id = 221;
UPDATE public.countries SET country = 'Poland', shortname = 'pl' WHERE id = 222;
UPDATE public.countries SET country = 'Portugal', shortname = 'pt' WHERE id = 223;
UPDATE public.countries SET country = 'Romania', shortname = 'ro' WHERE id = 224;
UPDATE public.countries SET country = 'Russian Federation', shortname = 'ru' WHERE id = 225;
UPDATE public.countries SET country = 'San Marino', shortname = 'sm' WHERE id = 226;
UPDATE public.countries SET country = 'Serbia', shortname = 'rs' WHERE id = 227;
UPDATE public.countries SET country = 'Slovakia', shortname = 'sk' WHERE id = 228;
UPDATE public.countries SET country = 'Slovenia', shortname = 'si' WHERE id = 229;
UPDATE public.countries SET country = 'Spain', shortname = 'es' WHERE id = 230;
UPDATE public.countries SET country = 'Sweden', shortname = 'se' WHERE id = 231;
UPDATE public.countries SET country = 'Switzerland', shortname = 'ch' WHERE id = 232;
UPDATE public.countries SET country = 'Ukraine', shortname = 'ua' WHERE id = 233;
UPDATE public.countries SET country = 'United Kingdom', shortname = 'gb' WHERE id = 234;
UPDATE public.countries SET country = 'Bouvet Island', shortname = 'bv' WHERE id = 235;
UPDATE public.countries SET country = 'British Indian Ocean Territory', shortname = 'io' WHERE id = 236;
UPDATE public.countries SET country = 'Canary Islands', shortname = 'ic' WHERE id = 237;
UPDATE public.countries SET country = 'Catalonia', shortname = 'catalonia' WHERE id = 238;
UPDATE public.countries SET country = 'England', shortname = 'england' WHERE id = 239;
UPDATE public.countries SET country = 'European Union', shortname = 'eu' WHERE id = 240;
UPDATE public.countries SET country = 'French Southern Territories', shortname = 'tf' WHERE id = 241;
UPDATE public.countries SET country = 'Guernsey', shortname = 'gg' WHERE id = 242;
UPDATE public.countries SET country = 'Heard Island and McDonald Islands', shortname = 'hm' WHERE id = 243;
UPDATE public.countries SET country = 'Isle of Man', shortname = 'im' WHERE id = 244;
UPDATE public.countries SET country = 'Jersey', shortname = 'je' WHERE id = 245;
UPDATE public.countries SET country = 'Kurdistan', shortname = 'kurdistan' WHERE id = 246;
UPDATE public.countries SET country = 'Scotland', shortname = 'scotland' WHERE id = 247;
UPDATE public.countries SET country = 'Somaliland', shortname = 'somaliland' WHERE id = 248;
UPDATE public.countries SET country = 'South Georgia and the South Sandwich Islands', shortname = 'gs' WHERE id = 249;
UPDATE public.countries SET country = 'Tibet', shortname = 'tibet' WHERE id = 250;
UPDATE public.countries SET country = 'United States Minor Outlying Islands', shortname = 'um' WHERE id = 251;
UPDATE public.countries SET country = 'Wales', shortname = 'wales' WHERE id = 252;
UPDATE public.countries SET country = 'Zanzibar', shortname = 'zanzibar' WHERE id = 253;