ALTER TABLE "pms"."flowrate"
	ALTER COLUMN "id" SET NOT NULL;
ALTER TABLE "pms"."flowrate" ADD PRIMARY KEY ("id") NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "pms"."o2_administration"
	ALTER COLUMN "id" SET NOT NULL;
ALTER TABLE "pms"."o2_administration" ADD PRIMARY KEY ("id") NOT DEFERRABLE INITIALLY IMMEDIATE;