CREATE TABLE "hospital_configuration"."hosp_opt_descharges_specialty" (
  "id" uuid NOT NULL,
  "typeofservice" int4,
  "nopatients" int4,
  "totallengthstay" int4,
  "nppay" int4,
  "nphservicecharity" int4,
  "nphtotal" int4,
  "phpay" int4,
  "phservice" int4,
  "phtotal" int4,
  "hmo" int4,
  "owwa" int4,
  "recoveredimproved" int4,
  "transferred" int4,
  "hama" int4,
  "absconded" int4,
  "unimproved" int4,
  "deathsbelow48" int4,
  "deathsover48" int4,
  "totaldeaths" int4,
  "totaldischarges" int4,
  "remarks" text,
  "reportingyear" int4,
  "created_by" varchar(50) COLLATE "pg_catalog"."default",
  "created_date" timestamp(6) DEFAULT now(),
  "last_modified_by" varchar(50) COLLATE "pg_catalog"."default",
  "last_modified_date" timestamp(6) DEFAULT now(),
  "deleted" bool,
  PRIMARY KEY ("id")
);