kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nexus-data-pv-claim-ebs
  namespace: nexus
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000G
