ALTER TABLE "inventory"."item" DROP COLUMN "economic_order_qty",
	DROP COLUMN "pharmacy_item",
	DROP COLUMN "stock_classification",
	DROP COLUMN "indication_code",
	DROP COLUMN "indication_desc",
	DROP COLUMN "medication_description",
	DROP COLUMN "route",
	DROP COLUMN "package_name",
	DROP COLUMN "package_content_count",
	DROP COLUMN "purchasing_item",
	DROP COLUMN "divisible_on_consumption",
	DROP COLUMN "dose",
	DROP COLUMN "dose_unit",
	DROP COLUMN "s2_drug",
	DROP COLUMN "form",
	DROP COLUMN "preparation",
	DROP COLUMN "distributor",
	DROP COLUMN "advocate",
	DROP COLUMN "category",
	DROP COLUMN "sub_category",
	DROP COLUMN "sub_sub_category",
	DROP COLUMN "formulary_item",
	DROP COLUMN "minimum_level";
ALTER TABLE "inventory"."item" RENAME COLUMN "item_dfa" TO "item_dfs";