CREATE TABLE IF NOT EXISTS hrm.salary_rate_multiplier(
	"id"                                                uuid NOT NULL PRIMARY KEY,
	"regular"                                           numeric DEFAULT 1,
	"restday"                                           numeric DEFAULT 1.3,
	"special_holiday"                                   numeric DEFAULT 1.3,
	"special_holiday_and_rest_day"                      numeric DEFAULT 1.5,
	"regular_holiday"                                   numeric DEFAULT 2,
	"regular_holiday_and_rest_day"                      numeric DEFAULT 2.6,
	"double_holiday"                                    numeric DEFAULT 3.3,
	"double_holiday_and_rest_day"                       numeric DEFAULT 3.9,
	"regular_overtime"                                  numeric DEFAULT 1.25,
	"restday_overtime"                                  numeric DEFAULT 1.69,
	"special_holiday_overtime"                          numeric DEFAULT 1.69,
	"special_holiday_and_rest_day_overtime"             numeric DEFAULT 1.95,
	"regular_holiday_overtime"                          numeric DEFAULT 2.6,
	"regular_holiday_and_rest_day_overtime"             numeric DEFAULT 3.38,
	"double_holiday_overtime"                           numeric DEFAULT 3.9,
	"double_holiday_and_rest_day_overtime"              numeric DEFAULT 5.07,
	"night_differential"                                numeric DEFAULT 0.1,
    created_by                                          varchar(50),
    created_date                                        timestamp(6) default CURRENT_TIMESTAMP,
    last_modified_by                                    varchar(50),
    last_modified_date                                  timestamp(6) default CURRENT_TIMESTAMP,
    deleted                                             boolean
);

INSERT INTO "hrm"."salary_rate_multiplier"
VALUES (
        '517f3f9a-1d19-4a33-8c91-3175d7f53914',
        '1',
        '1.3',
        '1.3',
        '1.5',
        '2',
        '2.6',
        '3.3',
        '3.9',
        '1.25',
        '1.69',
        '1.69',
        '1.95',
        '2.6',
        '3.38',
        '3.9',
        '5.07',
        '0.1',
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT
       );
