ALTER TABLE payroll.timekeepings
DROP COLUMN title,
DROP COLUMN description,
DROP COLUMN date_start ,
DROP COLUMN date_end  
;

DROP TABLE IF EXISTS payroll.accumulated_logs_summary;
CREATE TABLE payroll.accumulated_logs_summary (
    id                  uuid NOT NULL primary key,
    totals       		json NOT NULL,
	timekeeping_employee       uuid NOT NULL,
	foreign key (timekeeping_employee) references payroll.timekeeping_employees(id)
);

ALTER TABLE payroll.accumulated_logs
DROP COLUMN timekeeping_employee,
DROP COLUMN schedule_end,
DROP COLUMN schedule_start,
DROP COLUMN with_hazard_pay,
DROP COLUMN undertime,
DROP COLUMN late,
DROP COLUMN hours_absent,
DROP COLUMN worked,
DROP COLUMN hours_regular_overtime,
DROP COLUMN hours_worked_nsd,
DROP COLUMN worked_oic,
DROP COLUMN hours_regular_oic_overtime,
DROP COLUMN hours_worked_oic_nsd,
DROP COLUMN hours_rest_day,
DROP COLUMN hours_rest_day_nsd,
DROP COLUMN hours_rest_overtime,
DROP COLUMN hours_double_holiday,
DROP COLUMN hours_double_holiday_nsd,
DROP COLUMN hours_double_holiday_overtime,
DROP COLUMN hours_double_holiday_oic,
DROP COLUMN hours_double_holiday_oic_nsd,
DROP COLUMN hours_double_holiday_oic_overtime,
DROP COLUMN hours_double_holiday_and_rest_day,
DROP COLUMN hours_double_holiday_and_rest_day_overtime,
DROP COLUMN hours_double_holiday_and_rest_day_nsd,
DROP COLUMN hours_regular_holiday,
DROP COLUMN hours_regular_holiday_overtime,
DROP COLUMN hours_regular_holiday_nsd,
DROP COLUMN hours_regular_holiday_oic,
DROP COLUMN hours_regular_holiday_oic_overtime,
DROP COLUMN hours_regular_holiday_oic_nsd,
DROP COLUMN hours_regular_holiday_and_rest_day,
DROP COLUMN hours_regular_holiday_and_rest_day_overtime,
DROP COLUMN hours_regular_holiday_and_rest_day_nsd,
DROP COLUMN hours_special_holiday,
DROP COLUMN hours_special_holiday_overtime,
DROP COLUMN hours_special_holiday_nsd,
DROP COLUMN hours_special_holiday_oic,
DROP COLUMN hours_special_holiday_oic_overtime,
DROP COLUMN hours_special_holiday_oic_nsd,
DROP COLUMN hours_special_holiday_and_rest_day,
DROP COLUMN hours_special_holiday_and_rest_day_overtime,
DROP COLUMN hours_special_holiday_and_rest_day_nsd,
DROP COLUMN original_worked,
DROP COLUMN original_hours_regular_overtime,
DROP COLUMN original_hours_worked_nsd,
DROP COLUMN original_worked_oic,
DROP COLUMN original_hours_regular_oic_overtime,
DROP COLUMN original_hours_worked_oic_nsd,
DROP COLUMN original_hours_rest_day,
DROP COLUMN original_hours_rest_day_nsd,
DROP COLUMN original_hours_rest_overtime,
DROP COLUMN original_hours_double_holiday,
DROP COLUMN original_hours_double_holiday_nsd,
DROP COLUMN original_hours_double_holiday_overtime,
DROP COLUMN original_hours_double_holiday_oic,
DROP COLUMN original_hours_double_holiday_oic_nsd,
DROP COLUMN original_hours_double_holiday_oic_overtime,
DROP COLUMN original_hours_double_holiday_and_rest_day,
DROP COLUMN original_hours_double_holiday_and_rest_day_nsd,
DROP COLUMN original_hours_double_holiday_and_rest_day_overtime,
DROP COLUMN original_hours_regular_holiday,
DROP COLUMN original_hours_regular_holiday_nsd,
DROP COLUMN original_hours_regular_holiday_overtime,
DROP COLUMN original_hours_regular_holiday_oic,
DROP COLUMN original_hours_regular_holiday_oic_nsd,
DROP COLUMN original_hours_regular_holiday_oic_overtime,
DROP COLUMN original_hours_regular_holiday_and_rest_day,
DROP COLUMN original_hours_regular_holiday_and_rest_day_nsd,
DROP COLUMN original_hours_regular_holiday_and_rest_day_overtime,
DROP COLUMN original_hours_special_holiday,
DROP COLUMN original_hours_special_holiday_nsd,
DROP COLUMN original_hours_special_holiday_overtime,
DROP COLUMN original_hours_special_holiday_oic,
DROP COLUMN original_hours_special_holiday_oic_nsd,
DROP COLUMN original_hours_special_holiday_oic_overtime,
DROP COLUMN original_hours_special_holiday_and_rest_day,
DROP COLUMN original_hours_special_holiday_and_rest_day_nsd,
DROP COLUMN original_hours_special_holiday_and_rest_day_overtime,

ADD COLUMN summary uuid NOT NULL,
ADD COLUMN totals json NOT NULL,
ADD COLUMN department uuid NOT NULL,
ADD COLUMN schedule json NOT NULL,
ADD CONSTRAINT fk_summary FOREIGN KEY (summary) REFERENCES payroll.accumulated_logs_summary(id),
ADD CONSTRAINT fk_department FOREIGN KEY (department) REFERENCES public.departments(id)

;


