kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-data-pv-claim
  namespace: cm
  labels:
    app: cm-server
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
