package com.hisd3.hismk2.socket

enum HISD3MessageType {
	TEST_TYPE,
	NOTIFICATION_NEW,
	NOTIFICATION_RELOAD_,
	STOCK_REQUEST_LIST_NEW,
	STOCK_REQUEST_LIST_CLAIMABLE,
	STOCK_REQUEST_LIST_RELOAD,
	PAYROLL_CALCULATION_PROGRESS
}
