# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Welcome Message
        run:  echo CICD Test Runner



      - name: Build Docker
        run: |
            cd /runner/_work/hisd3-api/hisd3-api
            PROJ_VERSION=$(sudo /opt/gradle/bin/gradle properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}')
            echo "Project is ${PROJ_VERSION}"
            sudo /opt/gradle/bin/gradle build
            docker build -t "docker.ace-mc-bohol.com/hismk2_api:${PROJ_VERSION}" --build-arg PROJ_VERSION="${PROJ_VERSION}" .
            docker login -u builder -p M6msmXMa docker.ace-mc-bohol.com
            docker push "docker.ace-mc-bohol.com/hismk2_api:${PROJ_VERSION}"
